### ISSUE TITLE
ICONS - coming up blurry and wrong sizes. 

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#1]
Need them to be crisp like in the design. Revert to PNGs if you need to. Don't want us to spend any more time on this.

**Comment by tbrodahl** [comment]
![icons](https://cloud.githubusercontent.com/assets/5798011/20071275/ab0c76da-a4d8-11e6-9d6d-4c3cfd8db576.jpg)

**Comment by andrewmartin** [comment]
Which ones? The "start" and "graph" icons look extremely close, can we adjust the caret and hamburger and move on for now?

**Comment by tbrodahl** [comment]
I just want to make 100% sure that the icons are crisp and are the exact size as in the comps. 

---

I had a similar issue on a site i recently did with Scott - 

![screen shot 2016-10-16 at 11 31 51 am](https://cloud.githubusercontent.com/assets/5798011/20074928/098b65e6-a4e7-11e6-8f35-487d10990f78.png)

I think he was using fonts too. He figured it out in the end, maybe check with him if he has a trick for us?

**Comment by andrewmartin** [comment]
Like I said, I'm 95% sure the issue is aligning to a grid.

If we use an even number based grid, and aline the left and right edges of the icons to said grid, we won't have the partial `px` rendering issue.

Thanks for your patience on this, it was interesting to learn and I hope you see it as me going above and beyond and not trying to let my ego take over (I assure you, it's not the latter).
